"""Additional representative views, explicitly separated from as-built evidence."""
EXTRA_VIEWS=[]
def view(i,title,sub,items,edges,desc):EXTRA_VIEWS.append((str(i).zfill(2),title,sub,items,edges,desc))
def N(title,detail,icon=''):return(title,detail,icon)
BRANCH=[(0,1,0),(1,2,0),(2,5,0),(3,4,0),(4,5,0),(6,3,1),(7,4,1),(8,5,1)]
PIPE=[(i,i+1,0) for i in range(8)]
view(8,'Cloudflare / edge application','Edge delivery, application state, retrieval and private access.',[
N('Users / devices','Public apps · staff · service identities'),N('DNS / CDN / WAF','TLS · bots · DDoS · cache rules','cloudflare'),N('Workers / application','Request authorization · API logic','cloudflare'),N('Durable work','Queues · Durable Objects · retries','cloudflare'),N('Data & documents','R2 · D1 · KV · PostgreSQL','cloudflare'),N('AI / retrieval','AI Gateway · Workers AI · Vectorize','cloudflare'),N('Private access','Access · Tunnel · device posture','cloudflare'),N('Service operations','Logs · usage · errors · quotas'),N('Recovery / governance','Backups · lifecycle · runbooks')],BRANCH,'Resume-described Cloudflare components connected as a reference pattern. Public application authentication and employee Zero Trust access are distinct. Storage consistency, replay and recovery are designed per service.')
view(9,'Tailscale / private connectivity','Identity-based connectivity across people, sites and cloud workloads.',[
N('Identity provider','SSO · MFA · device authorization'),N('Tailnet control','Users · groups · tags · grants','tailscale'),N('Authorized devices','Posture · expiry · key lifecycle','tailscale'),N('Datacentre / LAN','Redundant subnet routers','tailscale'),N('Cloud workloads','Nodes · Kubernetes Operator','tailscale'),N('Remote workforce','Tailscale SSH · MagicDNS','tailscale'),N('Routing options','Subnet routes · exit nodes','tailscale'),N('Encrypted data paths','Direct WireGuard when possible'),N('Relay / audit','DERP fallback · logs · revocation')],[(0,1,0),(1,2,0),(1,3,0),(1,4,0),(2,5,0),(3,7,0),(4,7,0),(5,7,0),(6,7,1),(7,8,1)],'The control plane distributes identity and policy. Authorized endpoints carry encrypted traffic directly where possible, with DERP relay fallback. Subnet routers and exit nodes serve different routing purposes; application authorization remains necessary.')
view(10,'Oracle / full-stack cloud','From tenancy and private connectivity to applications, data and operations.',[
N('OCI tenancy / IAM','Compartments · policies · dynamic groups','oci-iam'),N('Private network','VCN · DRG · FastConnect · NSGs','oci-vcn'),N('Compute & platform','Bare metal / VMs · OKE · Functions','oci-compute'),N('Data services','Block / File / Object Storage','oci-storage'),N('Enterprise databases','Autonomous DB · Exadata · RAC','oci-database'),N('Business applications','APIs · WebLogic · Fusion integration'),N('Data movement','GoldenGate · Data Guard · OIC'),N('Security / telemetry','Cloud Guard · Vault · logs · metrics'),N('Recovery & lifecycle','Backups · failover · cost · patching')],BRANCH,'Resume-described OCI architecture. RAC addresses local database availability; Data Guard addresses replication and disaster-recovery patterns. SaaS integration, managed platform services and infrastructure ownership are distinct responsibilities.')
view(11,'IBM / hybrid enterprise','Connect Power, AIX and IBM i estates with cloud-native services.',[
N('Identity / network','IBM IAM · VPC · Direct Link'),N('Compute foundation','Bare Metal · Power Virtual Server'),N('Platform services','OpenShift · Kubernetes · Code Engine'),N('Operational data','Db2 · PostgreSQL · Object Storage'),N('Integration layer','MQ · Event Streams / Kafka'),N('Apps / analytics / AI','WebSphere · APIs · data consumers'),N('Legacy coexistence','IBM i · AIX · staged modernization'),N('Control plane','Key Protect · secrets · security'),N('Operations / recovery','Metrics · backup · service continuity')],BRANCH,'Resume-described IBM infrastructure, database and integration experience. The reference separates legacy coexistence from container modernization, with migration sequencing and recovery dependencies. Named services are alternatives selected per workload.')
view(12,'Alibaba Cloud / reference options','Requested extension for solution comparison; engagement evidence pending.',[
N('Identity & account','RAM · organization governance'),N('Network & edge','VPC · load balancing · CDN'),N('Compute & containers','ECS · ACK · serverless options'),N('Storage & state','OSS · block storage · databases'),N('Data & analytics','PolarDB · data integration options'),N('AI services','Model Studio · model access'),N('Protection','Keys · policies · security monitoring'),N('Delivery & operations','IaC · image registry · observability'),N('Recovery / economics','Backup · region strategy · budgets')],BRANCH,'Research/reference only: Alibaba Cloud is requested by the owner but is absent from the current resume. This comparison must not be interpreted as a completed Alibaba Cloud engagement. Exact regional services, editions and entitlements require workload-specific validation.')
view(13,'Bare metal / colocation','Physical provisioning through a supportable application platform.',[
N('Workload & facility','Capacity · rack · power · cooling'),N('Secure provisioning','Firmware · BMC · PXE / image'),N('Compute / storage','RAID · LUNs · fabric · multipath'),N('OS hardening','Linux / Windows · patch · baseline'),N('Network & identity','VLAN · routing · DNS · AD / LDAP'),N('Runtime & services','Hypervisor / containers / packages'),N('Lifecycle inventory','CMDB · warranty · asset retirement'),N('Operations / recovery','Metrics · backup · restore · NOC'),N('Acceptance','Load tests · failover · runbooks')],PIPE,'Physical and colocation architecture based on resume infrastructure scope. BMC isolation, boot-image integrity and PXE provisioning are design considerations, not claims of a specific unlisted installation. Facility Tier classification is separate from application availability.')
view(14,'Virtualization / private cloud','Separate compute, network, storage and operational failure domains.',[
N('Physical foundation','Servers · NICs · FC / IP fabrics'),N('Hypervisor alternatives','ESXi · Hyper-V · AHV · KVM'),N('Control & scheduling','vCenter · Prism · SCVMM · OpenStack'),N('Software-defined storage','vSAN · S2D · Ceph · SAN / NAS'),N('Network isolation','NSX · VLAN / VXLAN · firewalls'),N('Tenant workloads','VMs · templates · quotas · services'),N('Availability controls','HA · FT · DRS · live migration'),N('Backup / site recovery','Snapshots + independent backups'),N('Platform lifecycle','Patching · capacity · tests · handover')],BRANCH,'Resume-described virtualization alternatives. VMware Fault Tolerance, clustering, live migration and backup solve different failures; snapshots alone are not a backup strategy. Customer isolation and resource ownership are explicit.')
view(15,'Linux / UNIX / server services','Provision, secure and operate heterogeneous operating-system estates.',[
N('Distribution / support','RHEL · SUSE · Ubuntu · Debian'),N('OS baseline','systemd · SELinux / AppArmor'),N('Identity & access','LDAP · PAM · SSH · certificates'),N('Service packages','BIND · NGINX · Apache · mail'),N('Data & storage','LVM · NFS / SMB · databases'),N('Availability','Pacemaker · Corosync · HAProxy'),N('Automation','Ansible · shell · Puppet · Chef'),N('Health & protection','Patch · audit · metrics · backups'),N('Legacy coexistence','AIX · Solaris · HP-UX · IBM i')],BRANCH,'The resume names 13 Linux distribution families plus UNIX/IBM operating systems. This view preserves those boundaries instead of claiming 50+ variants. Kernel, NUMA, storage and network tuning follow workload measurements.')
view(16,'Zero Trust / IAM / PAM','Continuous authorization across identity, devices, workloads and data.',[
N('Identity lifecycle','JML · SSO · MFA · passkeys','entra'),N('Policy decisions','Risk · posture · entitlement · context'),N('Enforcement points','ZTNA · gateways · application auth'),N('Privileged access','PIM · PAM · JIT / JEA · vaulting'),N('Workload identity','Certificates · short-lived credentials'),N('Data authorization','RBAC / ABAC · DLP · encryption'),N('Evidence & review','Access reviews · SoD · audit'),N('Detection & response','SIEM · ITDR · XDR · revocation'),N('Recovery access','Break-glass · custody · tested restore')],BRANCH,'NIST SP 800-207-aligned reference. A private network is not automatically trusted. Policy applies to each resource request, with least privilege, device and workload context, monitored privileged sessions and recoverable identity dependencies.')
view(17,'SOC / MSSP / incident response','Turn telemetry into investigated, contained and learned-from incidents.',[
N('Telemetry sources','Endpoints · cloud · network · identity'),N('Collect & normalize','Connectors · schemas · enrichment'),N('Detect & correlate','SIEM · analytics · ATT&CK mappings','sentinel'),N('Investigate','Triage · hunting · evidence · scope'),N('Respond & contain','SOAR · XDR / EDR · approvals'),N('Recover business','Clean restore · validate · reconnect'),N('Threat intelligence','Hypotheses · indicators · purple team'),N('Case governance','Severity · SLAs · chain of custody'),N('Improve detections','Post-incident review · tuning · tests')],PIPE,'Resume-described SOC technologies include Sentinel, Defender XDR, CrowdStrike, Splunk, QRadar and Cortex XSOAR. MDR describes an operating service, not a synonym for an endpoint product. Automation follows approval and containment boundaries.')
view(18,'BCP / DR / cyber recovery','Plan business continuity, restore trusted services and prove failback.',[
N('Business impact','Criticality · dependencies · RPO/RTO'),N('Protect production','Veeam / Acronis / cloud backup'),N('Isolated copies','Immutable · offline · vault · retention'),N('Invoke continuity','People · communications · workarounds'),N('Clean-room recovery','Identity · network · apps · data'),N('Recovery validation','Malware checks · integrity · function'),N('Business acceptance','Dependency order · user sign-off'),N('Failback','Data reconciliation · controlled return'),N('Exercise & improve','Tabletop · restore test · evidence')],PIPE,'Resume evidence includes Veeam, Acronis, Rubrik, Commvault, Cohesity, Zerto, Datto, Veritas and IBM Tivoli. Backups, replication, disaster recovery and the broader business continuity plan are separate controls. Recovery tests provide evidence against agreed objectives.')
view(19,'HA / multi-site / multi-region','A five-nines target requires end-to-end failure and dependency analysis.',[
N('Global routing','Health checks · DNS / traffic policy'),N('Region / site A','Redundant application instances'),N('Region / site B','Independent failure domain'),N('Data replication','Sync / async · consistency trade-off'),N('Failover authority','Quorum · fencing · split-brain control'),N('Service continuity','Queues · retries · degraded modes'),N('External dependencies','Identity · DNS · carrier · vendors'),N('SLO measurement','End-to-end probes · error budgets'),N('Recovery exercises','Fault injection · failover · failback')],[(0,1,0),(0,2,0),(1,3,0),(2,5,0),(3,4,0),(4,5,0),(6,7,1),(7,4,1),(8,5,1)],'The resume reports 99.99%-class services. 99.999% is a design target requested for discussion, not a verified delivered result. Five nines permits about 5.26 minutes of annual unavailability over 365 days; maintenance exclusions and measurement boundaries belong in the SLA.')
view(20,'DevSecOps / software supply chain','Build once, verify evidence and progressively release signed artifacts.',[
N('Requirements & code','Threat model · review · branch policy'),N('CI validation','Unit / contract tests · SAST / SCA'),N('Build artifact','Container / package · SBOM · signing'),N('Policy & promotion','Provenance · secrets / IaC scan'),N('Deploy & reconcile','GitOps · admission · canary','githubactions'),N('Runtime assurance','DAST · telemetry · rollback criteria'),N('Supply-chain controls','SLSA · Sigstore · Cosign · in-toto'),N('Release decisions','Approvals · feature flags · evidence'),N('Feedback to backlog','Incidents · defects · dependency risk')],PIPE,'Resume-derived CI/CD, GitOps and supply-chain practices. Gates are concrete evidence checks. Build provenance, artifact identity and runtime controls remain traceable through release and rollback.')
view(21,'Platform engineering / IDP','Treat the internal developer platform as a product with measurable adoption.',[
N('Developer intent','Service template · catalog · ownership'),N('Platform API','Backstage · golden path · guardrails'),N('Provision foundation','Terraform / Bicep / CDK / Ansible'),N('Kubernetes fleet','AKS · EKS · GKE · OKE · OpenShift','k8s'),N('Delivery & policy','Helm · GitOps · OPA / Kyverno'),N('Operational product','SLOs · costs · documentation'),N('Platform security','Workload identity · secrets · scanning'),N('Developer experience','DORA · SPACE · onboarding time'),N('Platform roadmap','Feedback · adoption · scorecards')],BRANCH,'Resume-derived internal platform and fleet practices. Developer experience, provisioning time, reliability and adoption guide the roadmap; a collection of tools alone is not an internal developer platform.')
view(22,'SRE / observability / AIOps','Measure user journeys, reduce operational toil and learn from failures.',[
N('Service objectives','User journey · SLIs · SLOs · SLA'),N('Telemetry pipeline','OpenTelemetry · metrics / logs / traces'),N('Service signals','RED · USE · golden signals'),N('Detect & prioritize','Burn rate · symptoms · correlation'),N('Incident response','On-call · command · runbooks'),N('Restore & validate','Rollback · failover · user verification'),N('AIOps assistance','Anomaly / grouping · human oversight'),N('Capacity & resilience','Load / soak · chaos · saturation'),N('Improvement loop','Postmortem · error budget · toil')],PIPE,'Resume-described SRE and observability work. AIOps supports correlation and prioritization; privileged remediation remains controlled. Error-budget decisions connect reliability to delivery rather than treating uptime alone as the service outcome.')
view(23,'Database / distributed data','Choose consistency, availability and recovery deliberately.',[
N('Workload & contracts','OLTP / OLAP / HTAP · access pattern'),N('Data model','SQL · document · key/value · vector'),N('Transaction service','Indexes · pools · query plans'),N('Availability cluster','Always On · RAC · Patroni'),N('Replication / CDC','Data Guard · GoldenGate · Debezium'),N('Consumers','Apps · analytics · search · ML'),N('Protection','Encryption · PITR · immutable backup'),N('Scaling strategy','Partitioning · sharding · caching'),N('Recovery evidence','Failover · reconciliation · restore')],BRANCH,'Resume-derived database design and operations. Database products and replication models are alternatives; consistency, latency, data-loss windows and licensing determine selection. Analytics replicas and backups have separate recovery roles.')
view(24,'ML / LLM / SLM / AgentOps','Separate datasets, model artifacts, prompts, tools and runtime evidence.',[
N('Governed data','Quality · consent · version · labels'),N('Experiment & train','PyTorch · sklearn · LoRA / QLoRA'),N('Evaluate & register','MLflow · model cards · baselines'),N('Deploy / serve','vLLM · KServe · CPU / GPU'),N('Application runtime','RAG · agents · model routing'),N('Monitor & assess','Drift · quality · latency · spend'),N('Release controls','Dataset / prompt / tool versioning'),N('Feedback & retraining','Curated outcomes · approvals'),N('Recovery & rollback','Model fallback · checkpoints')],PIPE,'Resume evidence spans design, prototypes, evaluation and delivery; see individual project tiers. SLMOps applies lifecycle controls to small language models rather than implying a separate completed engagement. Training data, retrieval data and evaluation data must remain distinct.')
view(25,'Agent orchestration / MCP','Reasoning loops operate inside identity, policy and approval boundaries.',[
N('Request & context','Tenant · intent · budget · state'),N('Planner / graph','LangGraph · routes · checkpoints'),N('Proposed tool action','Typed schema · argument validation'),N('Policy / approval','Scopes · tool allowlist · human gate'),N('MCP / API execution','Scoped credentials · sandbox'),N('Observe tool result','Validate · persist · retry safely'),N('Grounded response','Citations · output checks · handoff'),N('Hooks & telemetry','Before / after tool · traces · costs'),N('Stop / resume','Iteration limits · interrupt · kill switch')],[(0,1,0),(1,2,0),(2,3,0),(3,4,0),(4,5,0),(5,1,1),(5,6,0),(7,4,1),(8,1,1)],'Reference expands resume-described agent loops, MCP, checkpoints and tool authorization. The policy gate must run before privileged execution. Hooks are extension points, not security guarantees. MCP provides a protocol; application authorization and replay-safe side effects remain design responsibilities.')
view(26,'ERP / CRM / enterprise automation','Connect commercial, finance, HR and inventory processes through controlled integration.',[
N('Business process','Lead-to-cash · procure-to-pay · HR'),N('Application suites','Odoo · Zoho · Dynamics · Fusion'),N('Integration contracts','APIs · Deluge · webhooks · events'),N('ERP operational data','Orders · inventory · finance · HR'),N('Workflow automation','Approvals · retries · reconciliation'),N('Reporting & AI','Governed metrics · document services'),N('Access & controls','SoD · role rights · audit · retention'),N('Extension options','SAP / Workday · scope-dependent'),N('Operations','Release · backup · support · adoption')],BRANCH,'Odoo, Zoho, Dynamics 365, Oracle Fusion and Workday integration appear in the resume. SAP is a requested reference extension with engagement detail pending. Vendor application catalogs describe possible modules; they do not establish implementation of every module.')
view(27,'Licensing / SAM / cloud economics','Translate user needs and workload rights into governed entitlements.',[
N('Inventory & demand','Users · devices · cores · workloads'),N('Rights assessment','Product terms · contracts · regions'),N('Select entitlements','M365 / Workspace · cloud / server'),N('Assign & configure','Groups · service plans · least privilege'),N('Measure consumption','Seats · tokens · cores · reservations'),N('Reconcile & optimize','True-up · reclaim · commitments'),N('Lifecycle controls','JML · renewal · BYOL eligibility'),N('Commercial evidence','SAM · audit trail · vendor negotiation'),N('Roadmap review','Retirements · new SKUs · exit cost')],PIPE,'Resume-described Microsoft, Google, VMware and cloud-commercial work. E7 is an evaluation in the source. Subscription tiers, license metrics, BYOL, support rights and region-specific product terms are assessed per contract; no universal licensing entitlement is implied.')
view(28,'Governance / GRC / assurance','Map obligations to controls, technical evidence and accountable decisions.',[
N('Scope & obligations','Jurisdiction · data · sector · contracts'),N('Risk assessment','Threat model · BIA · control gaps'),N('Control architecture','NIST · ISO · CSA · OWASP mappings'),N('Implement controls','Identity · encryption · segmentation'),N('Collect evidence','Policy as code · tests · audit logs'),N('Review & acceptance','Owners · exceptions · risk treatment'),N('Operational assurance','Continuous controls · incident learning'),N('Independent assurance','Audit / attestation where applicable'),N('Improve governance','Findings · roadmap · change control')],PIPE,'Resume-listed framework experience is not organizational certification or a legal compliance guarantee. Scope, jurisdiction, system boundary and independent assurance determine applicable obligations. Regulatory interpretation stays with the accountable business and legal functions.')
view(29,'Web / mobile / multi-tier apps','Distinguish presentation, application, integration and persistent data tiers.',[
N('User channels','Web · mobile · accessible UI'),N('Edge / identity','CDN · WAF · OIDC · session policy'),N('Application tier','Python / API · business rules'),N('Integration tier','Queues · workflows · external APIs'),N('Data tier','Transactions · cache · object storage'),N('Platform runtime','VMs / containers / serverless'),N('Device constraints','Offline sync · notifications · secrets'),N('Quality engineering','Contract / E2E · performance · security'),N('Release & support','Rollout · telemetry · version support')],BRANCH,'Representative application architecture. One-, two-, three- and four-tier deployment choices are different from datacentre Tier I–IV classifications and recovery criticality tiers. The resume supports web/API delivery; mobile-native implementation specifics remain unconfirmed.')
view(30,'Industry / edge / OT / physical AI','Connect operational assets to business systems without flattening safety boundaries.',[
N('Business outcome','Retail · plant · healthcare · aviation'),N('Field / OT assets','Sensors · PLC · SCADA · devices'),N('Edge gateway','Identity · protocol · offline buffering'),N('Secure conduit','Purdue zones · IEC 62443 boundary'),N('Business integration','MES / ERP · HL7 / FHIR awareness'),N('Cloud data & AI','Ingest · analytics · inference'),N('Fleet operations','Provision · OTA · configuration'),N('Human decisions','Safety · approvals · operational SOP'),N('Continuity','Local fallback · restore · support')],PIPE,'Resume evidence separates operational engineering from evaluated robotics, digital twins and physical AI. Domain protocols and regulatory needs vary by industry; the diagram is not a claim of clinical software ownership or safety certification.')
# Cloud-specific medallion implementations; each makes raw, validated and curated states explicit.
for i,title,bronze,silver,gold,ml,icon in [
(31,'Azure / Fabric / Databricks','ADLS / OneLake · ingestion','Databricks / Spark · validation','Delta tables · semantic models','Azure ML / Foundry','azure'),
(32,'AWS / lakehouse','S3 · DMS / Kinesis ingestion','Glue / EMR · quality transforms','Athena / Redshift · data products','SageMaker / Bedrock','aws'),
(33,'Google Cloud / analytics','Cloud Storage · Pub/Sub','Dataflow / Dataproc · validation','BigQuery / BigLake · metrics','Vertex AI / agent platform','gcp'),
(34,'Oracle / data platform','Object Storage · GoldenGate','Data Integration · quality rules','Autonomous DB · curated data','OCI Data Science / GenAI','oci-database'),
(35,'IBM / hybrid data','Object Storage · MQ / events','DataStage / Spark · validation','Db2 / lakehouse · data products','watsonx / model services','')]:
 view(i,title+' medallion','Bronze → Silver → Gold → analytics, ML features and controlled AI.',[
 N('Source systems','ERP · CRM · events · files · databases'),N('Bronze / raw',bronze,icon),N('Silver / validated',silver,icon),N('Gold / curated',gold,icon),N('Analytics consumers','Semantic layer · BI · authorized users'),N('ML & AI consumers',ml,icon),N('Governance plane','Catalog · lineage · access · retention'),N('Quality & operations','Contracts · freshness · replay · cost'),N('Release controls','Training / eval split · model rollback')],[(0,1,0),(1,2,0),(2,3,0),(3,4,0),(3,5,0),(6,1,1),(7,2,1),(8,5,1)],'Medallion is a data-quality design pattern, not a compulsory vendor product. Raw data is retained, silver is validated and standardized, and gold is curated for business use. ML features and permission-aware retrieval consume approved data; not all raw data goes directly to a model. This provider mapping is representative, not a separate claimed deployment.')
