"""Generate the static, single-page portfolio. No third-party build dependencies."""
import json
from html import escape as e
from pathlib import Path
from architecture import architecture_section, delivery_diagram, platform_strip
from portfolio_depth import depth_sections

ROOT = Path(__file__).resolve().parent
data = json.loads((ROOT / 'portfolio-data.json').read_text())
projects = data['projects']
categories = {
    'ai': list(range(1, 5)) + [35],
    'cloud': [5, 6, 7, 8, 21, 22, 23, 24],
    'platform': [9, 10, 11, 12, 13, 14, 15],
    'security': [16, 17, 18, 19, 20, 38],
    'data': [28, 29, 30, 31, 32, 33, 34, 41],
    'workplace': [25, 26, 27],
    'leadership': [36, 37, 39, 40],
}
labels = {'all':'All work', 'cloud':'Cloud & infrastructure', 'platform':'Platform & reliability', 'security':'Security', 'data':'Data & software', 'workplace':'Workplace', 'ai':'AI & automation', 'leadership':'Leadership & operations'}
tier_labels = {'T1':'Production delivery', 'T2':'Architecture & design', 'T3':'Prototype / POC / pilot', 'T4':'Training', 'T5':'Evaluation'}

cases = [
dict(id='01', domain='Retail & supply chain', role='Principal architect', title='A connected foundation for a growing retail business.',
 summary='Bring stores, employees, inventory and digital services together on a governed Microsoft and Azure foundation. My remit joined business discovery, architecture, engineering and operational readiness.',
 tags=['Microsoft & Azure', 'Retail operations', 'Cloud · data · security'],
 mandate='I owned architecture across cloud, infrastructure, security, data and AI, translating business needs into deployment standards, integration designs and operating procedures.',
 actions=['Designed Azure landing zones, identity controls, private connectivity and policy-driven governance.', 'Engineered container-platform patterns using AKS, Helm, infrastructure as code, workload identity and observability.', 'Designed a governed retail data foundation, inventory integration and permission-aware AI workflows.', 'Took agentic AI through a limited store pilot with evaluation, escalation and release controls.'],
 workflow=['Store & business needs', 'Identity & access', 'Data & integration', 'Applications & AI', 'Monitoring & support'],
 controls='Separate enterprise infrastructure scope from AI pilot scope. Identity, data permissions, security policy, service telemetry and recovery procedures span the design.',
 handover='Architecture decisions, infrastructure templates, deployment guides, pilot criteria, operational runbooks and technical enablement.',
 scope='The enterprise program and the limited AI pilot had different rollout boundaries. Detailed client topology and exact site counts are not disclosed here.'),
dict(id='02', domain='SaaS & technology', role='Fractional CTO', title='Turn an AWS estate into an executable product roadmap.',
 summary='Connect business priorities to architecture, investment and engineering decisions. I worked across AWS, AI and SaaS modernization, from current-state review to production-readiness planning.',
 tags=['AWS', 'Fractional leadership', 'SaaS modernization'],
 mandate='I directed technology strategy and architecture across cloud, applications, data, cybersecurity, AI, reliability and cost. Each platform choice was evaluated against the business and operating model.',
 actions=['Established current-state and target-state designs, dependency maps, architecture debt and investment sequencing.', 'Designed AWS multi-account governance, networking, identity, compute, containers, serverless and persistence patterns.', 'Defined Bedrock-based retrieval, model routing, scoped agent tools, evaluation and inference-cost controls.', 'Aligned tenancy, release engineering, observability, recovery and cloud economics with the modernization roadmap.'],
 workflow=['Business priorities', 'Architecture options', 'AWS foundation', 'Product & AI services', 'Operate & optimize'],
 controls='Make tenancy, security, availability and cost explicit. Select EC2, containers, serverless and managed data services according to workload needs, rather than combining every service.',
 handover='Investment roadmap, architecture options, decision records, implementation backlog, readiness criteria and operating-model guidance.',
 scope='Fractional strategy and architecture engagement. Individual designs, evaluations and implementation work are distinguished during a permitted technical discussion.'),
dict(id='03', domain='Managed technology services', role='Cloud & infrastructure architect', title='Many clients. Multiple clouds. Consistent delivery.',
 summary='Help service providers deliver secure, repeatable customer environments across Microsoft Azure, AWS, Google Cloud, IBM and Oracle—with the identity, networking and operations needed to connect them.',
 tags=['MSP · CSP · MSSP', 'Multi-cloud', 'Migration & operations'],
 mandate='I led discovery, architecture, technical qualification, implementation and escalation across customer and partner environments, bridging commercial requirements and engineering execution.',
 actions=['Designed cloud foundations, tenant isolation, delegated administration and customer-specific policy.', 'Worked across datacentres, networks, storage, databases, identity, cloud platforms and enterprise migrations.', 'Integrated security operations, monitoring, recovery and L1/L2/L3 escalation into service delivery.', 'Enabled partners with architecture workshops, proof-of-value environments, proposals, deployment guides and troubleshooting playbooks.'],
 workflow=['Customer qualification', 'Tenant & cloud foundation', 'Build or migrate', 'Service transition', 'Support & improvement'],
 controls='Customer boundaries, least privilege, change control, recovery sequencing and documented ownership support repeatable multi-tenant operations.',
 handover='Service catalog, deployment standards, migration waves, acceptance checks, SLA/OLA responsibilities and escalation runbooks.',
 scope='Multiple engagements across service-provider environments. Platform and scale details vary by customer and are not combined into a single fictional deployment.'),
dict(id='04', domain='Founder-owned product', role='Founder & hands-on builder', title='Build the product—and the systems that keep it running.',
 summary='Alfalah.app brings together product thinking, open-source software, multi-tenant architecture and AI-assisted workflows. I own the path from the initial idea to engineering, deployment and iteration.',
 tags=['Open-source foundations', 'Python & PostgreSQL', 'Product engineering'],
 mandate='I translate user needs into architecture and working software, combining product ownership with application, data, platform, security and AI engineering.',
 actions=['Built around Python, Django/FastAPI, PostgreSQL, pgvector, Redis, background workers and containers.', 'Designed tenant-aware identity, authorization, APIs, document workflows and retrieval boundaries.', 'Developed model-provider abstraction, evaluation, observability and cost-aware AI patterns.', 'Maintained deployment, testing, backup, runbooks and a roadmap separating working capability from future expansion.'],
 workflow=['User problem', 'Product & data model', 'Working vertical slice', 'Controlled release', 'Feedback & iteration'],
 controls='Tenant isolation, authorization checks, secrets, data retention, recovery and measurable model quality are core design concerns. Open-source software and managed hosting are distinct parts of the stack.',
 handover='Source code, architecture decisions, deployment configuration, operational guidance and an evolving product backlog.',
 scope='Founder-led product with iterative delivery. This portfolio does not present all roadmap features or intended global scale as verified live usage.'),
dict(id='05', domain='ISP & datacentre', role='Architect & L3/L4 engineer', title='Build the foundations that critical services depend on.',
 summary='From physical infrastructure and carrier connectivity to virtual platforms and hosted services, I built and operated systems across successive technology generations in continuously operating environments.',
 tags=['Datacentre & ISP', 'Legacy to cloud', '24×7 operations'],
 mandate='I progressed through systems administration, engineering and architecture, combining hands-on infrastructure work with availability, migration, capacity and operational accountability.',
 actions=['Worked across rack, power, cabling, compute, storage, networking and Tier I–IV datacentre environments.', 'Engineered Internet connectivity, routing, DNS, mail, web and database hosting with customer isolation.', 'Modernized physical estates through virtualization, private/hybrid cloud, automation and migration waves.', 'Operated incident escalation, backup/recovery, capacity planning and infrastructure lifecycle management.'],
 workflow=['Facility & carrier', 'Compute · storage · network', 'Identity & hosted services', 'Customer provisioning', 'Availability & recovery'],
 controls='Availability depends on the whole chain: facility, carrier, network, storage, operating system and application. Designs addressed redundancy, fault isolation, dependencies and recovery.',
 handover='Build standards, topology, provisioning procedures, migration plans, incident runbooks and recovery exercises.',
 scope='Experience includes critical and security-sensitive datacentre environments. No client identity, facility certification or personal security clearance is asserted by this description.'),
dict(id='06', domain='Legal & professional services', role='Systems architect', title='Move critical collaboration without losing business continuity.',
 summary='Modernize messaging, documents and identity while protecting the information people need every day. I combined migration engineering with access, retention, coexistence and operational transition.',
 tags=['Microsoft 365', 'Identity & migration', 'Information protection'],
 mandate='I designed and executed migration and hybrid-identity work, aligning technical cutover with information governance and user adoption.',
 actions=['Planned discovery, coexistence, pilot validation, migration waves and reconciliation.', 'Worked across Exchange Online, SharePoint Online, Teams, directory synchronization and hybrid identity.', 'Applied access controls, retention, legal-hold and auditability requirements to collaboration systems.', 'Prepared rollback contingencies, hypercare, administrator guidance and operational handover.'],
 workflow=['Inventory & access', 'Coexistence & pilot', 'Migration waves', 'Reconcile & validate', 'Adoption & support'],
 controls='Mailbox counts, user counts and document volume are distinct measures. Reconciliation, access verification and business validation determine migration acceptance.',
 handover='Migration and reconciliation records, identity design, administrative procedures, retention guidance and support ownership.',
 scope='An anonymized professional-services engagement. Client-specific volumes, topology and dates are withheld from the public case.'),
]

def tags(items): return '<div class="tags">'+''.join(f'<span class="tag">{e(x)}</span>' for x in items)+'</div>'
def render_case(c):
    return f'''<article class="case" id="case-{c['id']}"><div class="case-header"><div class="case-id"><span>{c['id']} / {e(c['domain'])}</span><span>{e(c['role'])}</span></div><h3>{e(c['title'])}</h3><p>{e(c['summary'])}</p>{tags(c['tags'])}</div><details><summary>Explore my role, architecture & delivery</summary><div class="case-content"><h4>My responsibility</h4><p>{e(c['mandate'])}</p><h4>What I did</h4><ul>{''.join('<li>'+e(a)+'</li>' for a in c['actions'])}</ul><h4>How the work connects</h4><p><a href="#architecture-{c['id']}">View the connected architecture diagram ↗</a></p><div class="flow" aria-label="Delivery workflow">{''.join('<span>'+e(a)+'</span>' for a in c['workflow'])}</div><h4>Architecture & controls</h4><p>{e(c['controls'])}</p><h4>Documentation & transition</h4><p>{e(c['handover'])}</p><p class="note">{e(c['scope'])}</p><div class="actions"><a href="mailto:shahzad.ms@yahoo.com?subject=Discuss%20portfolio%20case%20{c['id']}" class="btn">Discuss a similar challenge ↗</a></div></div></details></article>'''

PROJECT_VIEWS={1:25,2:24,3:24,4:28,5:13,6:1,7:2,8:10,9:21,10:21,11:20,12:20,13:22,14:22,15:19,16:16,17:17,18:16,19:18,20:28,21:14,22:9,23:15,24:14,25:6,26:27,27:16,28:31,29:31,30:23,31:33,32:29,33:26,34:4,35:26,36:22,37:27,38:28,39:28,40:28,41:30}

def render_project(p):
    cat = next(k for k,ids in categories.items() if p['id'] in ids)
    tier = ' · '.join(tier_labels[x.strip()] for x in p['evidence'].rstrip('.').split(',') if x.strip() in tier_labels)
    evaluated = f'<p class="evaluated"><strong>Evaluated / explored—not a claim of production use:</strong> {e(p["evaluated"])}</p>' if p['evaluated'] else ''
    return f'''<details class="project" id="project-{p['id']}" data-category="{cat}"><summary><span><span class="project-number">{p['id']:02d} / {e(labels[cat])}</span>{e(p['title'])}</span></summary><div class="project-body"><p class="evidence">{e(tier)}</p><ul>{''.join('<li>'+e(a)+'</li>' for a in p['actions'])}</ul>{evaluated}<p class="project-diagram-link"><a href="#architecture-{PROJECT_VIEWS[p['id']]:02d}">Explore related architecture ↗</a></p></div></details>'''

html = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102d35"><title>Shahzad MS | Enterprise Architect, Hands-on Technical Leader & Fractional CTO</title><meta name="description" content="34 years connecting business strategy with hands-on technology delivery. Enterprise architecture, cloud, datacentres, cybersecurity, software, data and AI. Available for roles, contracts and fractional leadership."><link rel="canonical" href="https://shahzadms7.github.io/"><meta property="og:title" content="Shahzad MS — From business challenge to working technology"><meta property="og:description" content="Enterprise architecture, hands-on engineering and fractional leadership. Explore 41 project families across infrastructure, cloud, security, software, data and AI."><meta property="og:type" content="website"><meta property="og:url" content="https://shahzadms7.github.io/"><link rel="icon" href="assets/icons/monogram.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/css/portfolio.css"><script defer src="assets/js/portfolio.js"></script><noscript><style>.nav-links{display:flex!important;position:static;flex-wrap:wrap;flex-direction:row;padding:8px;font-size:12px}.nav-inner{height:auto;min-height:68px;flex-wrap:wrap}.menu-button,.catalog-toolbar,.filters,#expand-projects,#print-profile{display:none!important}</style></noscript></head>
<body><div class="contact-bar"><div class="wrap"><span>SHAHZAD MS · CANADA · AVAILABLE NOW</span><div><a href="mailto:shahzad.ms@yahoo.com">shahzad.ms@yahoo.com</a><a href="https://github.com/shahzadms7">GitHub ↗</a><a href="https://www.linkedin.com/in/shahzadms/">LinkedIn ↗</a></div></div></div><a class="skip" href="#main">Skip to content</a><nav aria-label="Main navigation"><div class="wrap nav-inner"><a class="brand" href="#main" aria-label="Shahzad MS home"><span class="monogram" aria-hidden="true">SM</span>Shahzad MS<span style="color:var(--teal)">.</span></a><button class="menu-button" aria-expanded="false" aria-controls="navigation">Menu</button><div class="nav-links" id="navigation"><a href="#expertise">How I help</a><a href="#work">Selected work</a><a href="#architecture">Architecture</a><a href="#delivery">Delivery</a><a href="#catalog">Technical depth</a><a href="#contact" class="btn primary">Let’s talk ↗</a></div></div></nav>
<main id="main"><header class="hero"><div class="wrap"><div class="hero-grid"><div><div class="status">BASED IN CANADA · AVAILABLE FOR NEW ENGAGEMENTS</div><p class="eyebrow">Enterprise architect / Hands-on leader / Fractional CTO</p><h1>From business<br>challenge to<br><span>working technology.</span></h1><p class="intro">I help organizations modernize critical systems, build secure products and turn ambitious plans into reliable operations—from the first conversation to the final handover.</p><div class="actions"><a class="btn primary" href="mailto:shahzad.ms@yahoo.com?subject=Project%20or%20advisory%20inquiry">Discuss a project <span aria-hidden="true">↗</span></a><a class="btn" href="mailto:shahzad.ms@yahoo.com?subject=Employment%20or%20contract%20opportunity">Hire me <span aria-hidden="true">↗</span></a></div><p class="hero-meta">Employment · Contract · Fractional leadership · Consulting</p></div><aside class="portrait-card" aria-label="Meet Shahzad MS"><div class="portrait-top"><span>ARCHITECTURE + ENGINEERING</span><span>1992—2026</span></div><img src="assets/images/shahzad-ms.png" alt="Shahzad MS" width="430" height="580" fetchpriority="high"><div class="portrait-caption"><h2>Shahzad MS</h2><p>Principal Enterprise, Cloud & AI Architect</p><span>Executive perspective. Hands-on delivery.</span></div></aside></div><div class="browse-links" aria-label="Portfolio sections"><a href="#architecture">35 architecture views</a><a href="#service-models">Full-stack services</a><a href="#credentials">Credentials & training</a><a href="#career-library">Complete career record</a><a href="#industry-solutions">Industries</a></div><div class="metrics"><div class="metric"><strong>34 years</strong><span>Technology experience · 1992–2026</span></div><div class="metric"><strong>20+ years</strong><span>Architecture & technical leadership</span></div><div class="metric"><strong>41 areas</strong><span>Representative project families</span></div><div class="metric"><strong>End to end</strong><span>Discovery through operations</span></div></div>''' + platform_strip() + '''</div></header>
<section class="content" id="expertise"><div class="wrap"><div class="section-head"><div><p class="eyebrow">01 / How I help</p><h2>What does your<br>business need next?</h2></div><p>Start with the problem you need to solve. I connect executive decisions with the architecture, engineering and delivery needed to move forward.</p></div><div class="services">'''

services = [
('01','Make the next technology decision.','Assess your systems, compare options and turn uncertainty into a practical investment and delivery roadmap.','Architecture assessment · Fractional CTO/CIO','#contact'),
('02','Modernize without losing continuity.','Plan and deliver infrastructure, cloud, identity, email and application migrations with clear dependencies and recovery paths.','Datacentre · Cloud · Workplace migration','#case-05'),
('03','Build a product people can use.','Translate customer needs into a working product, secure APIs, dependable data and an actionable path from MVP to production.','Software · SaaS · Integration','#case-04'),
('04','Make systems safer and more reliable.','Connect identity, security, recovery and observability so teams can prevent problems and respond when they happen.','Cybersecurity · SRE · Resilience','#catalog'),
('05','Make AI useful in real work.','Find a valuable use case, connect the right data and evaluate a controlled pilot before expanding its responsibility.','AI · RAG · Agents · Automation','#case-01'),
('06','Extend your delivery capability.','Support customer discovery, proposals, architecture, implementation and complex escalation across partner and managed-service environments.','MSP · CSP · MSSP · Customer engineering','#case-03'),
]
for num,title,desc,sub,link in services:
    html += f'<article class="service"><span class="num">{num} /</span><h3>{e(title)}</h3><p>{e(desc)}</p><a href="{link}">Explore the approach ↗</a><small>{e(sub)}</small></article>'
html += '''</div></div></section><section class="content tinted" id="work"><div class="wrap"><div class="section-head"><div><p class="eyebrow">02 / Selected work</p><h2>Different environments.<br>Complete ownership.</h2></div><p>Six windows into my work across enterprise, service-provider and founder environments. Expand a story for responsibilities, architecture and delivery detail.</p></div><div class="case-grid">'''
html += ''.join(render_case(c) for c in cases)
html += '''</div><p class="note">Client identities and sensitive implementation details are withheld. These are anonymized experience summaries, not public client endorsements. Any deeper discussion remains subject to confidentiality obligations.</p></div></section>
''' + architecture_section() + '''<section class="content delivery" id="delivery"><div class="wrap"><div class="section-head"><div><p class="eyebrow">03 / My approach</p><h2>A clear path from<br>conversation to capability.</h2></div><p>You should know what we are solving, what will be delivered, how success is measured and who owns the system afterward.</p></div>''' + delivery_diagram() + '''<div class="steps">'''
steps = [
('01','Understand & agree','Listen to users and stakeholders. Map the current process, dependencies, constraints and business outcomes.','Outputs: discovery brief, scope of work, success criteria.'),
('02','Design & prove','Compare options, document architecture and test the uncertain parts through a prototype, POC or proof of value.','Outputs: architecture, decisions, threat model, evidence.'),
('03','Build & validate','Deliver the smallest useful end-to-end capability. Pilot with defined users, evaluate results and prepare for release.','Outputs: MVP, pilot report, test and readiness evidence.'),
('04','Operate & transfer','Deploy with recovery steps. Support adoption, document operations, train the receiving team and improve from feedback.','Outputs: as-built documentation, SOPs, runbooks, handover.'),
]
for num,title,desc,out in steps: html+=f'<div class="step"><b>{num}</b><h3>{title}</h3><p>{desc}</p><small>{out}</small></div>'
html += '''</div><details><summary>What enterprise readiness and handover actually include</summary><div class="sop"><p><strong>Define the service:</strong> users, transaction paths, data classification, dependencies, capacity, business owner and measurable availability, latency and recovery objectives.</p><p><strong>Control the release:</strong> access boundaries, security review, meaningful tests, restore validation, monitoring, versioned artifacts, cutover instructions and rollback criteria.</p><p><strong>Transfer responsibility:</strong> current architecture, configuration references, standard operating procedures, incident and recovery runbooks, support ownership, known issues and practical knowledge transfer.</p><p><strong>Close the loop:</strong> review adoption, service health, cost and business outcomes. A receiving team should be able to operate and recover the service. Stages are adapted to the engagement; an assessment or migration does not need an artificial product lifecycle.</p></div></details></div></section>
<section class="content" id="catalog"><div class="wrap"><div class="section-head"><div><p class="eyebrow">04 / Technical depth</p><h2>The breadth behind<br>the business outcomes.</h2></div><p>Explore 41 representative project families. Search a technology or discipline, then open a record for the engineering details and experience level.</p></div><div class="catalog-toolbar"><div class="search"><label class="sr-only" for="project-search">Search project families and technologies</label><input id="project-search" type="search" placeholder="Try: Active Directory, Terraform, migration, PostgreSQL…" autocomplete="off"></div><button class="btn" id="reset-search">Clear filters</button></div><div class="filters" role="group" aria-label="Filter project families">'''
html += ''.join(f'<button class="filter" data-filter="{k}" aria-pressed="{str(k=="all").lower()}">{e(v)}</button>' for k,v in labels.items())
html += '''</div><p class="legend">Experience levels distinguish production delivery, architecture/design, prototypes or pilots, training and evaluation. A project family can span several engagements and levels; an evaluated tool is not presented as production experience. Detailed architecture and client evidence are discussed only within permitted confidentiality boundaries.</p><div class="result-line"><span id="result-count" role="status" aria-live="polite">41 of 41 project families</span><button id="expand-projects" class="filter">Expand visible details</button></div><div class="catalog">'''
html += ''.join(render_project(p) for p in projects)
html += '</div><h3 class="technology-heading" style="margin:40px 0 14px">Technology & capability inventory</h3><p class="note" style="margin-bottom:20px">A broader index of historical platforms, implementation tools, architecture methods and evaluated technologies. Inclusion does not imply production use, certification or current product availability. Match these areas to a specific engagement in our technical discussion.</p><div class="catalog">'
skill_categories = ['workplace','workplace','cloud','cloud','cloud','cloud','platform','data','security','data','ai','data','leadership','security','leadership']
for i, skill in enumerate(json.loads((ROOT/'technology-data.json').read_text())):
    html += f'<details class="project technology" id="technology-{i+1}" data-category="{skill_categories[i]}"><summary><span><span class="project-number">TECHNOLOGY INVENTORY / {i+1:02d}</span>{e(skill["title"])}</span></summary><div class="project-body"><p class="evidence">Across delivery, design, training and evaluation; ask for engagement-specific depth.</p><p class="evaluated">{e(skill["terms"])}</p></div></details>'
html += '''</div><p class="empty" id="no-results" hidden>No matching project families. Try a broader term or clear the filters.</p><p class="note">This is an experience catalog, not a claim that every technology was used in every engagement. Historical platforms are retained where they explain modernization experience. Public GitHub repositories are separate from confidential client implementations.</p></div></section>
<section class="content tinted" id="experience"><div class="wrap"><div class="history-layout"><div class="history-intro"><p class="eyebrow">05 / Experience & perspective</p><h2>Built on foundations.<br>Always moving forward.</h2><p>My career connects the physical systems that keep services running with the cloud, software and AI platforms that move businesses forward.</p><p>I work at both levels: explaining an investment decision to a business owner and working through a technical problem with the engineering team.</p><div class="actions"><a class="btn" href="mailto:shahzad.ms@yahoo.com?subject=Request%20current%20resume">Request my resume ↗</a><button class="btn" id="print-profile">Print profile</button></div><p><a class="btn" href="#credentials">Read credentials, education & training ↓</a></p></div><div class="timeline">'''
eras=[('1992 onward','A foundation in technology','Systems, software and infrastructure foundations; continuous learning across successive technology generations.'),('2000–2019','ISP, systems & datacentre engineering','Hands-on operations through architecture: carrier networks, hosted services, storage, virtualization, recovery and hybrid modernization.'),('2020','Enterprise migration & workplace','Messaging, collaboration, identity, information governance and service transition in professional services.'),('2021–2025','Multi-cloud & managed-service architecture','Customer and partner delivery across cloud, datacentres, cybersecurity, migrations, platform engineering and operations.'),('2023 onward','Founder-led product engineering','Product strategy, open-source software, multi-tenancy, APIs, data, AI and iterative delivery through Alfalah.app.'),('2025–2026','Enterprise & fractional technology leadership','Microsoft/Azure enterprise architecture and AWS/SaaS advisory, connecting executive priorities with engineering and AI delivery.')]
for year,title,desc in eras: html+=f'<div class="era"><time>{e(year)}</time><h3>{e(title)}</h3><p>{e(desc)}</p></div>'
html+='''</div></div><div class="industries"><h3>Scale, capacity & continuity</h3><p>Experience across large estates includes 5,000+ virtual machines, 1,000+ physical servers, millions of directory objects and identities, and 25,000+ mailbox migrations across engagements. These describe different estate and career measures—not one client deployment.</p><p>Vertical and horizontal scaling connect compute, memory, storage, replicas, load balancing, partitioning and asynchronous workloads. Capacity planning, bottleneck analysis, failover, recovery and cost determine the right approach.</p></div><div class="industries"><h3>Across business models and industries</h3><p>Banking & insurance · Manufacturing · Government & public services · Legal & professional services · Retail & supply chain · Healthcare · Aviation & transportation · Telecom & ISP · SaaS & enterprise software · Media · Nonprofit · Recruitment</p><p>B2B · B2C · B2B2C · IaaS · PaaS · SaaS · Managed, cloud and security services</p><p class="note">Industry and service-model experience spans different engagements; it does not imply each model was delivered for every client.</p></div></div></section>
''' + depth_sections() + '''<section class="content" id="engagements"><div class="wrap"><div class="section-head"><div><p class="eyebrow">06 / Work together</p><h2>The right engagement<br>for the work ahead.</h2></div><p>From a focused assessment to embedded delivery or ongoing leadership, start with a clear problem and agree on a practical scope.</p></div><div class="engagements"><div><h3>Employment & contracts</h3><p>Senior architecture, hands-on engineering, technical leadership and customer-facing delivery. Share the role and the outcomes you need.</p></div><div><h3>Scoped projects</h3><p>Assessment, architecture, migration, integration, MVP or remediation—with deliverables, acceptance criteria and handover agreed upfront.</p></div><div><h3>Fractional & advisory</h3><p>CTO/CIO guidance, architecture reviews, investment decisions, roadmap ownership, vendor evaluation and team enablement.</p></div><div><h3>Partner & startup work</h3><p>MSP/CSP/MSSP delivery support, technical qualification and product collaboration. Selected cash-plus-equity advisory considered.</p></div></div></div></section>
<section class="content contact" id="contact"><div class="wrap contact-grid"><div><p class="eyebrow">Let’s start with your challenge</p><h2>What are you trying<br>to make possible?</h2><p>Tell me what you need to build, improve or lead, your timing and the kind of help you are looking for. We can turn that into a useful next conversation.</p><div class="contact-info">Greater Toronto Area, Canada · Remote opportunities<br>Incorporated in Canada · Available for new engagements</div></div><div class="contact-links"><a href="mailto:shahzad.ms@yahoo.com?subject=Let%E2%80%99s%20discuss%20an%20opportunity"><span>Email me<small>shahzad.ms@yahoo.com</small></span><span aria-hidden="true">↗</span></a><a href="https://www.linkedin.com/in/shahzadms/"><span>Connect on LinkedIn<small>Experience & professional background</small></span><span aria-hidden="true">↗</span></a><a href="https://github.com/shahzadms7"><span>Explore my GitHub<small>Public repositories & technical work</small></span><span aria-hidden="true">↗</span></a><a href="mailto:shahzad.ms@yahoo.com?subject=Arrange%20an%20introductory%20call"><span>Arrange an introductory call<small>Send your preferred time and topic</small></span><span aria-hidden="true">↗</span></a></div></div></section></main><footer><div class="wrap footer-inner"><span>© 2026 Shahzad MS · Architecture. Engineering. Delivery.</span><span>Client confidentiality respected · <a href="#main">Back to top ↑</a></span></div></footer></body></html>'''

(ROOT / 'index.html').write_text(html)
(ROOT / 'assets/icons/monogram.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="15" fill="#102d35"/><text x="32" y="40" text-anchor="middle" fill="#d3f499" font-size="25" font-family="sans-serif" font-weight="bold">SM</text></svg>')

# Keep historical bookmarks working without retaining outdated case-study claims.
for filename, target in {'index.html':'catalog','sol-01-azure-foundry.html':'case-01','sol-02-aws-bedrock.html':'case-02','sol-03-gcp-gemini.html':'case-03','sol-04-anthropic-claude.html':'project-1','sol-05-opensource-rag.html':'case-04'}.items():
    (ROOT/'solutions'/filename).write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=../index.html#{target}"><link rel="canonical" href="https://shahzadms7.github.io/"><title>Shahzad MS — Portfolio updated</title></head><body><p>This case is now part of the complete portfolio. <a href="../index.html#{target}">View the updated portfolio</a>.</p></body></html>')
print(f'Built index.html with {len(cases)} engagement stories and {len(projects)} project families.')
