from pathlib import Path
from html import escape as e
import json
ROOT=Path(__file__).parent

def disclosure(title,body,klass='depth-card',id=''):
 return f'<details class="{klass}"'+(f' id="{id}"' if id else '')+f'><summary>{e(title)}</summary><div class="depth-body">{body}</div></details>'
def section(id,kicker,title,intro,body):
 return f'<section class="content depth-section" id="{id}"><div class="wrap"><div class="section-head"><div><p class="eyebrow">{e(kicker)}</p><h2>{e(title)}</h2></div><p>{e(intro)}</p></div>{body}</div></section>'
def table(headers,rows):
 return '<div class="table-scroll" tabindex="0" role="region" aria-label="'+e(headers[0])+' comparison"><table><thead><tr>'+''.join('<th scope="col">'+e(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'

def depth_sections():
 records=json.loads((ROOT/'career-source-data.json').read_text());byid={int(r['id'][1:]):r for r in records};out=[]
 models=[
 ('Azure','VMs / VMSS · VNet · disks / storage','AKS · App Service · Functions · Azure SQL','Custom SaaS tenancy / APIs; M365 & Dynamics integration','Entra · Policy · Monitor · Defender · Backup / ASR'),
 ('AWS','EC2 · VPC · EBS / EFS / S3','EKS / ECS · Lambda · RDS / Aurora','Custom SaaS control/data planes; billing & entitlements','IAM · Organizations · CloudWatch · Backup / DRS'),
 ('Google Cloud','Compute Engine · VPC · disks / storage','GKE · Cloud Run · Cloud SQL / BigQuery','Custom SaaS services; Workspace integration','IAM · Org Policy · Monitoring · Backup and DR'),
 ('Oracle OCI','Bare metal / VMs · VCN · storage','OKE · Functions · Autonomous Database','Custom SaaS / WebLogic services; Fusion integration','Compartments · IAM · Cloud Guard · Vault · recovery'),
 ('IBM / hybrid','Bare metal · Power VS · VPC · storage','OpenShift · Kubernetes · managed databases','Enterprise apps and custom SaaS; MQ integration','IAM · secrets · security governance · monitoring'),
 ('Cloudflare','Edge/network services; not a generic VM estate','Workers · Durable Objects · R2 / D1 / KV','Edge SaaS APIs, tenancy, metering and model routing','Access · WAF · DDoS · logs · export/restore design'),
 ('Private / hybrid cloud','Servers · SAN / NAS · carrier / LAN','VMware · Hyper-V · AHV · OpenStack · Kubernetes','Hosted applications, multi-tenant services and APIs','Directory · segmentation · NOC / SOC · DR site'),
 ('Alibaba — reference','ECS · VPC · OSS','ACK · managed database / serverless options','Potential SaaS deployment; personal evidence pending','RAM · monitoring · backup · regional requirements')]
 out.append(section('service-models','Full-stack delivery','Infrastructure, platforms and applications.','IaaS, PaaS and SaaS describe responsibility boundaries—not three labels for the same implementation.',table(['Environment','IaaS / infrastructure','PaaS / application platform','SaaS / business application','Cross-cutting controls'],models)+'<p class="note">Every design also covers provisioning, tenant lifecycle, capacity, availability, security, data lifecycle, licensing, release, monitoring, support, recovery and exit. The research extension is clearly identified; product alternatives are not asserted as one combined deployment.</p>'))
 licensing=[('Microsoft 365 / Office 365','E1 / E3 / E5; F1 / F3; Business Basic / Standard / Premium; A1 / A3 / A5; G1 / G3 / G5','Group licensing, service plans, true-up, coexistence, tenant migration. E7 / Agent 365 / Copilot are source-described evaluations.'),('Microsoft security / endpoint','Entra P1/P2 / Governance / Suite; Defender plans; Purview; Intune; Windows 365 / AVD','Map users, devices, workloads and add-ons to rights; separate historical product names from current offers.'),('Microsoft business apps','Power BI; Power Apps / Automate premium; Dynamics 365; Copilot Studio','Environment, connector, capacity, user and consumption requirements; selected terms determine rights.'),('Google Workspace','Business / Enterprise / Essentials / Frontline / Education / Nonprofits; Cloud Identity; Chrome Enterprise','Seat allocation, OU policy, security, Vault, data regions, Gemini-era edition changes and renewals.'),('Cloud / server / database','Microsoft EA; AWS EDP; VMware; Windows Server / SQL; Oracle; Linux subscriptions','SAM inventory, core/device/user metrics, BYOL eligibility, support, audit evidence, reservations and usage.'),('Open source / managed SaaS','Community and commercial editions; hosting, support, redistribution and model licenses','License compatibility, obligations, portability, TCO and entitlement review. Open source is not synonymous with zero operating cost.')]
 out.append(section('licensing','Commercial and operational ownership','Licensing, entitlement and technology economics.','A product list is only the starting point: inventory, rights, consumption and lifecycle decisions must connect.',table(['Portfolio area','Source-aligned product families','Delivery responsibilities'],licensing)))
 creds=[]
 for title,nums in [('Education',[418,419,420]),('Microsoft credentials and training',[423]),('AWS credentials and training',[425]),('Google Cloud, cybersecurity and governance',[427]),('Virtualization, platform and analytics',[429]),('AI learning, events and development',[431]),('Awards, pending exams and roadmap',[433]),('Foundational and vendor training',[435])]:
  body=''.join('<p>'+e(byid[n]['text'])+'</p>' for n in nums)
  creds.append(disclosure(title,body))
 out.append(section('credentials','Credentials and continuing development','The learning behind the delivery.','The complete resume-listed record, with pending exams and development plans kept distinct from earned credentials.','<p class="note">These are owner-supplied resume records, not independently verified active badges. Issue dates, expiry dates and transcripts are not present. Google Professional Cloud Architect is marked examination-ready; SC-100 and CISSP exams are pending. EX200/EX294 are exam identifiers, not proof of an earned RHCSA/RHCE credential.</p><div class="depth-grid">'+''.join(creds)+'</div><p class="note">The source names training and hackathon programs but does not provide a complete webinar/seminar attendance log. Exact event title, organizer, date, role and evidence are needed to add those records. The AWS ML Specialty 2027 plan requires revision; see the dated lifecycle review below.</p>'))
 industries=[('Banking / capital markets',394),('Insurance / reinsurance',396),('Government / public administration',398),('Defence / sensitive systems',400),('Aviation / critical infrastructure',402),('Healthcare / life sciences',404),('Legal / immigration / tax',406),('Manufacturing / heavy industry',408),('MSP / CSP / MSSP / ISP',410),('Software / SaaS / vendors',412),('Retail / ecommerce / supply chain',414),('Media / travel / recruitment / nonprofit',416)]
 out.append(section('industry-solutions','Business environments','Technology in the context of the industry.','The technical work is tied to business processes, continuity and information needs, while client identities remain confidential.','<div class="depth-grid">'+''.join(disclosure(t,'<p>'+e(byid[n]['text'])+'</p>') for t,n in industries)+'</div>'))
 records_by_group={}
 for rec in records:records_by_group.setdefault(rec['group'],[]).append(rec)
 archive='<div class="archive-controls"><label for="career-search">Search the complete resume-derived record</label><input type="search" id="career-search" placeholder="Try: Oracle RAC, Acronis, SUSE, E7, CISM, LangGraph…"><p id="career-count" role="status" aria-live="polite">725 source records accounted for</p></div><div id="career-groups">'
 for group,rr in records_by_group.items():
  body=''.join(f'<div class="evidence-record" id="source-{r["id"]}"><small>{e(r["id"])} · {e(r["basis"])}</small><p>{e(r["text"])}</p></div>' for r in rr)
  archive+=disclosure(group+' · '+str(len(rr))+' records',body,'career-group depth-card')
 archive+='</div><p class="note">Source: ShahzadMS_Resume_2026_v08.docx, reviewed 1 September 2026. Every non-empty body paragraph and table paragraph has a disposition. Identifiers are withheld and sensitive detail is generalized; technical terms remain traceable. <a href="coverage-audit.json">View source coverage register</a>. Accounting for a source record does not certify the underlying claim or imply exhaustive knowledge of a vendor catalog.</p>'
 out.append(section('career-library','Complete source coverage','The detailed career record.','Read beyond summaries: responsibilities, platforms, methods, project tiers, leadership, training and historical experience.',archive))
 extensions=json.loads((ROOT/'solution-extensions.json').read_text())
 out.append(section('solution-extensions','Expanded solution coverage','Beyond the current resume.','Additional requested areas and design checks are retained here, with their evidence boundary visible.','<div class="depth-grid">'+''.join(disclosure(x['title'],'<span class="reference-badge">Solution / reference coverage</span><p><strong>Scope:</strong> '+e(x['scope'])+'</p><p><strong>Delivery:</strong> '+e(x['delivery'])+'</p><p><strong>Evidence:</strong> '+e(x['evidence'])+'</p><p><a href="'+e(x['url'])+'">Relevant official source ↗</a></p>') for x in extensions)+'</div>'))
 research=json.loads((ROOT/'research-data.json').read_text())
 out.append(section('current-reference','Official-source review / 1 September 2026','Current products and lifecycle checks.','Current research supports product naming and design options. It does not create new personal experience.','<div class="depth-grid">'+''.join(disclosure(x['title'],'<p>'+e(x['summary'])+'</p><p><a href="'+e(x['url'])+'">Official source ↗</a> · Checked '+x['checked']+'</p>') for x in research)+'</div>'))
 manifests=json.loads((ROOT/'service-icon-manifest.json').read_text())
 out.append(section('product-icons','Service identity','Product-specific architecture icons.','Official service artwork is retained unchanged. Some Google Cloud symbols come from its explicitly labelled legacy package; names remain visible.','<details class="depth-card"><summary>Browse '+str(len(manifests))+' additional service icons</summary><div class="icon-library">'+''.join('<div><img loading="lazy" src="assets/icons/'+e(x['file'])+'" width="48" height="48" alt=""><span>'+e(x['product'])+'</span></div>' for x in manifests)+'</div></details><p class="note"><a href="ICON_SOURCES.md">Sources and attribution</a>. Provider marks and generic pictograms are not substituted for a different product’s official mark.</p>'))
 return ''.join(out)
